I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 145, in script call
    call dialogue_scene_1
  File "game/script.rpy", line 187, in script
    call screen establish_connection_game
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/script.rpy", line 88, in execute
    screen establish_connection_game:
  File "game/script.rpy", line 88, in execute
    screen establish_connection_game:
  File "game/script.rpy", line 97, in execute
    draggroup:
  File "game/script.rpy", line 107, in execute
    for i in range(wave_pieces):
  File "game/script.rpy", line 108, in execute
    drag:
  File "game/script.rpy", line 108, in keywords
    drag:
  File "game/script.rpy", line 113, in <module>
    pos piece_coordinates[i]
NameError: name 'piece_coordinates' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 145, in script call
    call dialogue_scene_1
  File "game/script.rpy", line 187, in script
    call screen establish_connection_game
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 1968, in execute
    self.call("execute")
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\ast.py", line 1950, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\exports.py", line 3413, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\core.py", line 2165, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\core.py", line 2687, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\core.py", line 2687, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\kt201\RenPy\renpy-8.2.1-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/script.rpy", line 88, in execute
    screen establish_connection_game:
  File "game/script.rpy", line 88, in execute
    screen establish_connection_game:
  File "game/script.rpy", line 97, in execute
    draggroup:
  File "game/script.rpy", line 107, in execute
    for i in range(wave_pieces):
  File "game/script.rpy", line 108, in execute
    drag:
  File "game/script.rpy", line 108, in keywords
    drag:
  File "game/script.rpy", line 113, in <module>
    pos piece_coordinates[i]
NameError: name 'piece_coordinates' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Observatoria 1.0
Sun Apr  7 20:42:20 2024
