I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script call
    call dialogue_scene_1
  File "game/script.rpy", line 47, in script call
    call observation_game.run_observation_game
  File "game/script.rpy", line 29, in script call
    call dialogue_scene_1
  File "game/script.rpy", line 47, in script call
    call observation_game.run_observation_game
ScriptError: could not find label 'observation_game.run_observation_game'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script call
    call dialogue_scene_1
  File "game/script.rpy", line 47, in script call
    call observation_game.run_observation_game
  File "C:\Users\kt201\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1416, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 29, in script call
    call dialogue_scene_1
  File "game/script.rpy", line 47, in script call
    call observation_game.run_observation_game
  File "C:\Users\kt201\Downloads\renpy-8.2.1-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'observation_game.run_observation_game'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
Observatoria 1.0
Thu Mar 21 18:29:00 2024
